[angles]
right_knee = [ "hip_center", "right_knee", "right_ankle",]
left_knee = [ "hip_center", "left_knee", "left_ankle",]
right_ankle = [ "right_knee", "right_ankle", "right_foot",]
left_ankle = [ "left_knee", "left_ankle", "left_foot",]
right_wrist = [ "right_elbow", "right_wrist", "right_paw",]
left_wrist = [ "left_elbow", "left_wrist", "left_paw",]
right_elbow = [ "right_shoulder", "right_elbow", "right_wrist",]
left_elbow = [ "left_shoulder", "left_elbow", "left_wrist",]
